name: Docker

on:
  push:
    branches: main

jobs:
  docker_build:
    environment: docker-hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Lint pyspark-emr-6-corretto-8
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: pyspark-emr-6-corretto-8/Dockerfile
          failure-threshold: error

      - name: Run privileged
        run: sudo docker run --privileged --rm tonistiigi/binfmt --install arm64

      - name: Build pyspark-emr-6-corretto-8
        id: docker_build_1
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./pyspark-emr-6-corretto-8
          file: ./pyspark-emr-6-corretto-8/Dockerfile
          push: false
          tags: infrahelpers/cloud-python:pyspark-emr-6
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build pyspark-emr-6-light-multi-platform
        id: docker_build_2
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./pyspark-emr-6-corretto-11-light
          file: ./pyspark-emr-6-corretto-11-light/Dockerfile
          push: true
          tags: infrahelpers/cloud-python:pyspark-emr-6-light-multi-platform
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Build pyspark-emr-corretto-11
        id: docker_build_3
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./pyspark-emr-corretto-11
          file: ./pyspark-emr-corretto-11/Dockerfile
          push: false
          tags: infrahelpers/cloud-python:pyspark-emr-jdk11
          cache-from: type=gha
          cache-to: type=gha,mode=max

