name: Docker

on:
  push:
    branches: patch-1
  pull_request:
    branches: main

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Lint pyspark-emr-6-coretto-8
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: pyspark-emr-6-coretto-8/Dockerfile
          failure-threshold: error

      - name: Run privileged
        run: sudo docker run --privileged --rm tonistiigi/binfmt --install arm64,riscv64,arm

      # - name: Build pyspark-emr-6-coretto-8
      #   id: docker_build_1
      #   uses: docker/build-push-action@v3
      #   with:
      #     builder: ${{ steps.buildx.outputs.name }}
      #     context: ./pyspark-emr-6-coretto-8
      #     file: ./pyspark-emr-6-coretto-8/Dockerfile
      #     push: false
      #     tags: infrahelpers/cloud-python:pyspark-emr-6
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      - name: Build pyspark-emr-6-coretto-8-light
        id: docker_build_2
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./pyspark-emr-6-coretto-8-light
          file: ./pyspark-emr-6-coretto-8-light/Dockerfile
          push: false
          tags: infrahelpers/cloud-python:pyspark-emr-6-light
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      # - name: Build pyspark-emr-6-coretto-8-light-arm
      #   id: docker_build_3
      #   uses: docker/build-push-action@v3
      #   with:
      #     builder: ${{ steps.buildx.outputs.name }}
      #     context: ./pyspark-emr-6-coretto-8-light-arm
      #     file: ./pyspark-emr-6-coretto-8-light-arm/Dockerfile
      #     push: false
      #     tags: infrahelpers/cloud-python:pyspark-emr-6-light-arm
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
      #     platforms: linux/arm64

      # - name: Build pyspark-emr-coretto-11
      #   id: docker_build_3
      #   uses: docker/build-push-action@v3
      #   with:
      #     builder: ${{ steps.buildx.outputs.name }}
      #     context: ./pyspark-emr-coretto-11
      #     file: ./pyspark-emr-coretto-11/Dockerfile
      #     push: false
      #     tags: infrahelpers/cloud-python:pyspark-emr-jdk11
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
